
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=blog_database
      - DB_USER=xena
      - DB_PASSWORD=123456
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: blog_database
      POSTGRES_USER: xena
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: