# Generated by Django 5.1.2 on 2024-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_text',
            field=models.TextField(),
        ),
    ]
