# Generated by Django 5.1.2 on 2024-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_story_story_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_date',
            field=models.DateField(auto_now=True),
        ),
    ]
